import re
from dataclasses import dataclass
from typing import Any

import ollama

from bot.config import BotConfig


@dataclass
class LLMResponse:
    """Structured response from the LLM service."""

    content: str
    reaction: str | None = None
    raw: dict[str, Any] | None = None


class OllamaService:
    """
    Encapsulates interaction with the Ollama local LLM, including prompt construction,
    inference execution, <think> block removal, and reaction parsing.
    """

    def __init__(self, config: BotConfig, client: ollama.AsyncClient | None = None) -> None:
        self.config = config
        if client is not None:
            self.client = client
        elif config.ollama_host:
            self.client = ollama.AsyncClient(host=config.ollama_host)
        else:
            self.client = ollama.AsyncClient()

    @staticmethod
    def clean_think_tags(text: str) -> str:
        """Strips leftover <think>...</think> reasoning blocks if generated by thinking models."""
        return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

    @staticmethod
    def extract_reaction(text: str) -> tuple[str | None, str]:
        """
        Parses LLM-chosen Discord reaction emoji if present in the format:
        [REACTION: <single_emoji_or_NONE>]
        Returns a tuple of (reaction_emoji_or_None, cleaned_text).
        """
        reaction_match = re.match(r"^\[REACTION:\s*([^\]]+)\]", text)
        if reaction_match:
            raw_emoji = reaction_match.group(1).strip()
            clean_text = text[reaction_match.end():].strip()
            if raw_emoji.upper() == "NONE" or not raw_emoji:
                return None, clean_text
            return raw_emoji, clean_text

        return None, text

    def build_messages_payload(
        self,
        history: list[dict[str, str]],
        formatted_user_prompt: str,
    ) -> list[dict[str, str]]:
        """Constructs the structured messages list for Ollama chat API."""
        payload: list[dict[str, str]] = [{"role": "system", "content": self.config.system_prompt}]
        payload.extend(history)
        payload.append({"role": "user", "content": formatted_user_prompt})
        return payload

    async def generate_response(
        self,
        history: list[dict[str, str]],
        formatted_user_prompt: str,
    ) -> LLMResponse:
        """
        Calls Ollama asynchronously and extracts cleaned content and reaction emoji.
        """
        messages_payload = self.build_messages_payload(history, formatted_user_prompt)

        response = await self.client.chat(
            model=self.config.ollama_model,
            messages=messages_payload,
            think=False,
            options={
                "temperature": self.config.temperature,
                "top_p": self.config.top_p,
                "min_p": getattr(self.config, "min_p", 0.07),
                "repeat_penalty": getattr(self.config, "repeat_penalty", 1.08),
                "num_predict": self.config.num_predict,
                "num_ctx": getattr(self.config, "num_ctx", 8192),
            },

        )

        raw_content = response.get("message", {}).get("content", "").strip()
        cleaned_content = self.clean_think_tags(raw_content)
        reaction, final_reply = self.extract_reaction(cleaned_content)

        return LLMResponse(content=final_reply, reaction=reaction, raw=response)
